### ISSUE TITLE
Json unmarshal error

### ISSUE THREAD

**Issue by spartan117aut** [IvanKuchin/phpipamsync#12]
Hi,

thanks for adding #9 so quickly. While testing, I ran into this error:

> 2024/01/29 14:58:26.941661 get.go:28: Error unmarshalling json: json: cannot unmarshal number into Go struct field Ipam_subnet_data.data.id of type string
> Error: json: cannot unmarshal number into Go struct field Ipam_subnet_data.data.id of type string
> Usage:
>   phpipamsync get pi-hole [flags]
> 
> Flags:
>   -h, --help   help for pi-hole
> 
> Error: json: cannot unmarshal number into Go struct field Ipam_subnet_data.data.id of type string

I then tried it again with version 0.1.2 but got the same error. So I suspect it has to do with the update of phpipam that I did meanwhile. My phpipam version is: v1.6.0 git 97bc4d97

I have no experience with go, but I played around a little and found that I probably could get rid of the errors by setting the datatype to int for the respective variables in internal/cli/get_types.go

**Comment by IvanKuchin** [comment]
since 1.6 phpipam has changed json-schema.
The problem has been fixed.

**Comment by spartan117aut** [comment]
Thanks, now it works.
