### ISSUE TITLE
Multiple subnets

### ISSUE THREAD

**Issue by spartan117aut** [IvanKuchin/phpipamsync#9]
Hi @IvanKuchin,

thanks for this program, I got it working. Does it support multiple subnets? If yes, how do you specify them in the config file?
I tried various ways but couldn't get it to work.

Thanks.

**Comment by IvanKuchin** [comment]
Hello, 
Thank you for the feedback. 
It doesn't as of today.  
I'll add that feature.

**Comment by IvanKuchin** [comment]
Hello @spartan117aut ,

Feature added. 
Notice that the config syntax has changed. New syntax is

```
ipam_subnets: 
- 192.168.250.0/24
- 192.168.251.0/24
```
